# Generated by Django 3.1 on 2023-09-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20230913_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Catrgories'},
        ),
    ]
